use crate::{
    common::Id,
    edge::{EdgeId, EdgeKind},
    entity_type::{EntityTypeId, EntityTypes},
    process::{
        ProcessDiagram, ProcessId, ProcessStepId, ProcessSteps, Processes, StepDescs,
        StepThingInteractions,
    },
    tag::{TagId, TagNames, TagThings},
    theme::{
        Css, CssClassPartials, IdOrDefaults, StyleAlias, StyleAliases, ThemeAttr, ThemeDefault,
        ThemeStyles, ThemeTagThingsFocus, ThemeTagThingsFocusSpecific,
        ThemeThingDependenciesStyles, ThemeTypesStyles, ThingsFocusStyles,
    },
    thing::{
        ThingCopyText, ThingDependencies, ThingDependenciesDescs, ThingHierarchy, ThingId,
        ThingInteractions, ThingNames,
    },
    InputDiagram,
};

/// Structure that represents the OpenAPI documentation for the Disposition API.
#[derive(utoipa::OpenApi)]
#[openapi(components(schemas(
    Css,
    CssClassPartials,
    EdgeId,
    EdgeKind,
    EntityTypeId,
    EntityTypes,
    Id,
    IdOrDefaults,
    InputDiagram,
    TagId,
    TagNames,
    TagThings,
    ProcessDiagram,
    ProcessId,
    ProcessStepId,
    ProcessSteps,
    Processes,
    StepDescs,
    StepThingInteractions,
    StyleAlias,
    StyleAliases,
    ThemeAttr,
    ThemeDefault,
    ThemeStyles,
    ThemeTagThingsFocus,
    ThemeTagThingsFocusSpecific,
    ThemeThingDependenciesStyles,
    ThemeTypesStyles,
    ThingCopyText,
    ThingDependencies,
    ThingDependenciesDescs,
    ThingHierarchy,
    ThingId,
    ThingInteractions,
    ThingNames,
    ThingsFocusStyles,
)))]
pub struct ApiDoc;
